require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'HesabeMerchant' do

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
 
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'


  pod 'react-native-cameraroll', :path => '../node_modules/@react-native-community/cameraroll'
  




  pod 'RNQuickAction', :path => '../node_modules/react-native-quick-actions'
  




  target 'HesabeMerchantTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  permissions_path = '../node_modules/react-native-permissions/ios'
  
  use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
  #use_flipper!
  #post_install do |installer|
    #flipper_post_install(installer)
  #end
  
   pod 'pop', '~> 1.0'
   pod 'IQKeyboardManagerSwift'
   pod 'Toast-Swift', '~> 5.0.1'
   pod 'TrustKit'
   pod 'Firebase/Analytics'
   pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
end

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 3.0', '< 4.0'
end

target 'HesabeMerchant-tvOS' do
  # Pods for HesabeMerchant-tvOS

  target 'HesabeMerchant-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
